/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutOrdersIndexRouteImport } from './routes/_layout/orders/index'
import { Route as LayoutUsersSplatRouteImport } from './routes/_layout/users.$'
import { Route as LayoutOrdersOrderIdIndexRouteImport } from './routes/_layout/orders/$orderId/index'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutOrdersIndexRoute = LayoutOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUsersSplatRoute = LayoutUsersSplatRouteImport.update({
  id: '/users/$',
  path: '/users/$',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutOrdersOrderIdIndexRoute =
  LayoutOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/users/$': typeof LayoutUsersSplatRoute
  '/orders': typeof LayoutOrdersIndexRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/users/$': typeof LayoutUsersSplatRoute
  '/orders': typeof LayoutOrdersIndexRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/users/$': typeof LayoutUsersSplatRoute
  '/_layout/orders/': typeof LayoutOrdersIndexRoute
  '/_layout/orders/$orderId/': typeof LayoutOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/$' | '/orders' | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/$' | '/orders' | '/orders/$orderId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/users/$'
    | '/_layout/orders/'
    | '/_layout/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/orders/': {
      id: '/_layout/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/users/$': {
      id: '/_layout/users/$'
      path: '/users/$'
      fullPath: '/users/$'
      preLoaderRoute: typeof LayoutUsersSplatRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/orders/$orderId/': {
      id: '/_layout/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof LayoutOrdersOrderIdIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutUsersSplatRoute: typeof LayoutUsersSplatRoute
  LayoutOrdersIndexRoute: typeof LayoutOrdersIndexRoute
  LayoutOrdersOrderIdIndexRoute: typeof LayoutOrdersOrderIdIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutUsersSplatRoute: LayoutUsersSplatRoute,
  LayoutOrdersIndexRoute: LayoutOrdersIndexRoute,
  LayoutOrdersOrderIdIndexRoute: LayoutOrdersOrderIdIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
